name: AQI Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Docker Buildx
      - uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t aqi-streamlit:latest .

      # Tag and push to Docker Hub
      - name: Tag & Push Docker image
        run: |
          docker tag aqi-streamlit:latest ${{ secrets.DOCKER_USERNAME }}/aqi-streamlit:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/aqi-streamlit:latest

      # Deploy to remote server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/aqi-streamlit:latest
            docker stop aqi_app || true
            docker rm aqi_app || true
            docker run -d -p 8501:8501 --name aqi_app ${{ secrets.DOCKER_USERNAME }}/aqi-streamlit:latest
